# Site settings
title: The Good Tom Chi
email: contact@thegoodtomchi.com
description: > # The personal website of Tom Chi. Get involved or learn something new.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thegoodtomchi.com" # the base hostname & protocol for your site
twitter_username: thegoodtomchi
github_username:  thegoodtomchi

# Build settings
markdown: kramdown
